[build]
target = "x86_64-kur_os.json"

[target.x86_64-kur_os]
runner = "bootimage runner"

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]
panic-abort-tests = true 